In [2]:
from fastai import *
import pandas as pd
from google.colab import userdata
import os
import zipfile

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

import kaggle

In [4]:
dataset_id = 'darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily'
path = 'ticker_list'
kaggle.api.dataset_download_cli(dataset_id, path = str(path), unzip=True, force=True)

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily
License(s): CC0-1.0
Downloading s-and-p-500-stocks-25-years-of-data-updated-daily.zip to ticker_list

100%|██████████| 100M/100M [00:05<00:00, 18.9MB/s]

In [5]:
!ls {path}

sp500_companies.csv  sp500_stocks.csv

In [9]:
tk = pd.read_csv('ticker_list/sp500_companies.csv')
tk.head()

,symbol,company,sector,sub_industry,headquarters,date_added,founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1989

In [10]:
import numpy as np
tickers = tk['symbol'].tolist()
tickers[0:25]

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE']

In [11]:
import yfinance as yf
df = yf.download(tickers, period="3mo")
df.head()

/tmp/ipykernel_753/88378548.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, period="3mo")
[*********************100%***********************]  503 of 503 completed

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2026-04-27  115.398041  267.363647  195.985016  141.059998  92.142815
2026-04-28  114.649483  270.460815  196.292816  139.039993  93.195305
2026-04-29  111.086334  269.921326  202.448990  140.279999  90.683220
2026-04-30  115.328178  271.100250  209.826492  140.360001  90.147041
2026-05-01  114.300148  279.882141  205.139847  141.660004  88.826462

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2026-04-27  96.349998  174.867355  239.309998  391.517578  70.077965  ...
2026-04-28  97.059998  175.638092  243.199997  382.213074  72.323166  ...
2026-04-29  92.720001  178.118256  243.570007  388.246552  73.783531  ...
2026-04-30  94.459999  176.586685  246.100006  401.161194  74.051765  ...
2026-05-01  93.820000  177.693375  250.710007  396.603668  74.449150  ...

Price        Volume                                                         \
Ticker           WY     WYNN      XEL       XOM      XYL      XYZ      YUM
Date
2026-04-27  3505500  1175000  3892000  13940800  2983600  3991200  2854500
2026-04-28  3987800  1083900  3790500  15173600  3360600  4507400  3013400
2026-04-29  5619400  1352700  3719000  14669100  2660800  4924800  3177300
2026-04-30  8281500  1086800  9105500  22885900  2543000  4106200  1878700
2026-05-01  7384500  1466300  5345900  15458200  1872000  3808600  1589100

Price
Ticker          ZBH     ZBRA      ZTS
Date
2026-04-27  2503800   738700  3160300
2026-04-28  9823700   760600  2972500
2026-04-29  5242800   891400  3395900
2026-04-30  4169700  1016000  4297200
2026-05-01  2724100   655900  3204000

[5 rows x 2515 columns]

In [ ]:
closes = df["Close"]
returns = closes.pct_change() *100

cs = closes.stack().rename("Close")
rs = returns.stack().rename("Returns")
fdf = pd.concat([cs,rs], axis = 1).reset_index()

fdf.columns = ['date', 'ticker', 'close', 'return']
fdf = fdf.dropna(subset=['return'])

fdf.head(25)

In [ ]:
len(fdf)

In [ ]:
df = fdf

df['lag 1'] = df['return'].shift(1)