<a href="https://colab.research.google.com/github/Suman-Poola/Random-Forrest-s-p500/blob/main/XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from fastai import *
import pandas as pd
from google.colab import userdata
import os
import zipfile

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

import kaggle

In [2]:
dataset_id = 'darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily'
path = 'ticker_list'
kaggle.api.dataset_download_cli(dataset_id, path = str(path), unzip=True, force=True)

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily
License(s): CC0-1.0
Downloading s-and-p-500-stocks-25-years-of-data-updated-daily.zip to ticker_list

100%|██████████| 99.9M/99.9M [00:03<00:00, 31.5MB/s]

In [3]:
!ls {path}

sp500_companies.csv  sp500_stocks.csv

In [4]:
tk = pd.read_csv('ticker_list/sp500_companies.csv')
tk.head()

,symbol,company,sector,sub_industry,headquarters,date_added,founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1989

In [5]:
import numpy as np
tickers = tk['symbol'].tolist()
tickers[0:25]

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE']

In [6]:
len(tickers)

503

In [7]:
tickers[499:503]

['YUM', 'ZBRA', 'ZBH', 'ZTS']

In [8]:
import yfinance as yf
df = yf.download(tickers, period="36mo")
df.head()

/tmp/ipykernel_3059/2136594173.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, period="36mo")
[*********************100%***********************]  503 of 503 completed

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2023-08-22  114.983856  174.864914  133.651260  127.080002  98.782768
2023-08-23  116.440224  178.703018  132.605392  128.130005  98.763962
2023-08-24  116.792076  174.026260  132.199677  124.720001  97.467537
2023-08-25  116.977798  176.226517  132.253754  125.790001  97.899673
2023-08-28  117.212379  177.785431  132.920914  126.154999  96.565643

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2023-08-22  70.908501  292.468781  519.479980  168.299362  73.060760  ...
2023-08-23  71.697754  298.566193  530.710022  169.080521  73.386398  ...
2023-08-24  71.707260  297.430023  512.429993  165.469879  72.662773  ...
2023-08-25  70.956047  301.804260  525.059998  169.728348  73.115028  ...
2023-08-28  70.547165  303.839874  529.919983  171.795639  73.151230  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2023-08-22  4728200  2296400  3142600  10518800   833700  10494000  1207700
2023-08-23  3083400  1298600  8610700  11435600  1012500  12207300  1441600
2023-08-24  1858400  1494000  5780900  10818500   896800   7952700  1131100
2023-08-25  2768500  1706200  7705600  13579300   973800   7741000  1097300
2023-08-28  1360500  1209800  3982200  10382100   803600   5333600  1815600

Price
Ticker          ZBH    ZBRA      ZTS
Date
2023-08-22  3648900  340500  1286400
2023-08-23  2755200  314800  1022900
2023-08-24  1953000  246300  1210300
2023-08-25  1456700  337300   879700
2023-08-28  2658500  211000  1546900

[5 rows x 2515 columns]

In [9]:
closes = df["Close"]
returns = closes.pct_change() *100

cs = closes.stack().rename("Close")
rs = returns.stack().rename("Returns")
fdf = pd.concat([cs,rs], axis = 1).reset_index()

fdf.columns = ['date', 'ticker', 'close', 'return']
fdf = fdf.dropna(subset=['return'])

fdf.head(25)

/tmp/ipykernel_3059/2048977385.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = closes.pct_change() *100

          date ticker       close    return
495 2023-08-23      A  116.440224  1.266584
496 2023-08-23   AAPL  178.703018  2.194897
497 2023-08-23   ABBV  132.605392 -0.782535
498 2023-08-23   ABNB  128.130005  0.826254
499 2023-08-23    ABT   98.763962 -0.019038
500 2023-08-23   ACGL   71.697754  1.113059
501 2023-08-23    ACN  298.566193  2.084808
502 2023-08-23   ADBE  530.710022  2.161785
503 2023-08-23    ADI  169.080521  0.464148
504 2023-08-23    ADM   73.386398  0.445708
505 2023-08-23    ADP  233.848267  0.557039
506 2023-08-23   ADSK  204.360001  1.884534
507 2023-08-23    AEE   73.214706  0.024922
508 2023-08-23    AEP   71.284119  1.030258
509 2023-08-23    AES   15.815268  2.004455
510 2023-08-23    AFL   68.653267 -0.299748
511 2023-08-23    AIG   53.930355  0.488314
512 2023-08-23    AIZ  132.674393  0.158342
513 2023-08-23    AJG  218.983276  1.445178
514 2023-08-23   AKAM  102.440002  1.195297
515 2023-08-23    ALB  183.159180  1.923895
516 2023-08-23   ALGN  359.480011  2.232462
517 2023-08-23    ALL   98.936172  0.475657
518 2023-08-23   ALLE  106.290192  2.449214
519 2023-08-23   AMAT  144.570847  0.318577

fdf.sort_values(by=['ticker', 'date'], inplace=True)
fdf.head(25)

In [10]:
fdf_appl = fdf[fdf['ticker'] == 'AAPL'].copy()
fdf_appl.head()

           date ticker       close    return
496  2023-08-23   AAPL  178.703018  2.194897
991  2023-08-24   AAPL  174.026260 -2.617056
1486 2023-08-25   AAPL  176.226517  1.264324
1981 2023-08-28   AAPL  177.785431  0.884608
2476 2023-08-29   AAPL  181.663010  2.181044

In [11]:
len(fdf_appl)

752

In [12]:
fdf_appl['Lag 1'] = fdf_appl['close'].shift(1)
fdf_appl['Lag 2'] = fdf_appl['close'].shift(2)
fdf_appl['Lag 3'] = fdf_appl['close'].shift(3)
fdf_appl['Lag 5'] = fdf_appl['close'].shift(5)
fdf_appl.head(25)

,date,ticker,close,return,Lag 1,Lag 2,Lag 3,Lag 5
496,2023-08-23,AAPL,178.703018,2.194897,NaN,NaN,NaN,NaN
991,2023-08-24,AAPL,174.026260,-2.617056,178.703018,NaN,NaN,NaN
1486,2023-08-25,AAPL,176.226517,1.264324,174.026260,178.703018,NaN,NaN
1981,2023-08-28,AAPL,177.785431,0.884608,176.226517,174.026260,178.703018,NaN
2476,2023-08-29,AAPL,181.663010,2.181044,177.785431,176.226517,174.026260,NaN
2971,2023-08-30,AAPL,185.145874,1.917212,181.663010,177.785431,176.226517,178.703018
3466,2023-08-31,AAPL,185.362961,0.117252,185.145874,181.663010,177.785431,174.026260
3961,2023-09-01,AAPL,186.931717,0.846316,185.362961,185.145874,181.663010,176.226517
4456,2023-09-05,AAPL,187.168518,0.126678,186.931717,185.362961,185.145874,177.785431
4951,2023-09-06,AAPL,180.469162,-3.579318,187.168518,186.931717,185.362961,181.663010
5446,2023-09-07,AAPL,175.190552,-2.924938,180.469162,187.168518,186.931717,185.145874
5941,2023-09-08,AAPL,175.802246,0.349159,175.190552,180.469162,187.168518,185.362961
6436,2023-09-11,AAPL,176.966476,0.662239,175.802246,175.190552,180.469162,186.931717
6931,2023-09-12,AAPL,173.947342,-1.706049,176.966476,175.802246,175.190552,187.168518
7426,2023-09-13,AAPL,171.885254,-1.185467,173.947342,176.966476,175.802246,180.469162
7921,2023-09-14,AAPL,173.394806,0.878232,171.885254,173.947342,176.966476,175.190552
8416,2023-09-15,AAPL,172.674576,-0.415370,173.394806,171.885254,173.947342,175.802246
8911,2023-09-18,AAPL,175.595047,1.691315,172.674576,173.394806,171.885254,176.966476
9406,2023-09-19,AAPL,176.680389,0.618094,175.595047,172.674576,173.394806,173.947342
9901,2023-09-20,AAPL,173.148163,-1.999218,176.680389,175.595047,172.674576,171.885254
10396,2023-09-21,AAPL,171.608963,-0.888950,173.148163,176.680389,175.595047,173.394806
10891,2023-09-22,AAPL,172.457474,0.494444,171.608963,173.148163,176.680389,172.674576
11386,2023-09-25,AAPL,173.730286,0.738044,172.457474,171.608963,173.148163,175.595047
11881,2023-09-26,AAPL,169.665268,-2.339844,173.730286,172.457474,171.608963,176.680389
12376,2023-09-27,AAPL,168.155670,-0.889751,169.665268,173.730286,172.457474,173.148163

In [13]:
fdf_appl['SMA 5'] = fdf_appl['close'].rolling(window=5).mean()
fdf_appl['SMA 10'] = fdf_appl['close'].rolling(window=10).mean()
fdf_appl['SMA 20'] = fdf_appl['close'].rolling(window=20).mean()
fdf_appl['SMA 30'] = fdf_appl['close'].rolling(window=30).mean()
fdf_appl['SMA 50'] = fdf_appl['close'].rolling(window=50).mean()

fdf_appl.head(100)
#fdf_appl = fdf[fdf['ticker'] == 'AAPL'].copy()
#fdf_appl.head()

,date,ticker,close,return,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50
496,2023-08-23,AAPL,178.703018,2.194897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,2023-08-24,AAPL,174.026260,-2.617056,178.703018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,2023-08-25,AAPL,176.226517,1.264324,174.026260,178.703018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,2023-08-28,AAPL,177.785431,0.884608,176.226517,174.026260,178.703018,NaN,NaN,NaN,NaN,NaN,NaN
2476,2023-08-29,AAPL,181.663010,2.181044,177.785431,176.226517,174.026260,NaN,177.680847,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47587,2024-01-09,AAPL,182.910065,-0.226312,183.324951,178.997726,179.718948,183.404007,181.396487,185.339424,189.364352,189.337017,185.741107
48083,2024-01-10,AAPL,183.947372,0.567114,182.910065,183.324951,178.997726,182.030746,181.779813,184.661682,189.019061,189.218462,186.100551
48579,2024-01-11,AAPL,183.354584,-0.322260,183.947372,182.910065,183.324951,179.718948,182.506940,183.914784,188.568552,189.060059,186.407292
49075,2024-01-12,AAPL,183.680618,0.177816,183.354584,183.947372,182.910065,178.997726,183.443518,183.158006,187.973801,188.946443,186.711082
49571,2024-01-16,AAPL,181.418228,-1.231698,183.680618,183.354584,183.947372,183.324951,183.062173,182.278725,187.258523,188.738314,186.906479

In [14]:
fdf_appl['volatility 5'] = fdf_appl['return'].rolling(5).std()
fdf_appl['volatility 10'] = fdf_appl['return'].rolling(10).std()
fdf_appl['volatility 20'] = fdf_appl['return'].rolling(20).std()
fdf_appl['volatility 30'] = fdf_appl['return'].rolling(30).std()
fdf_appl.head()

,date,ticker,close,return,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30
496,2023-08-23,AAPL,178.703018,2.194897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,2023-08-24,AAPL,174.026260,-2.617056,178.703018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,2023-08-25,AAPL,176.226517,1.264324,174.026260,178.703018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,2023-08-28,AAPL,177.785431,0.884608,176.226517,174.026260,178.703018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2476,2023-08-29,AAPL,181.663010,2.181044,177.785431,176.226517,174.026260,NaN,177.680847,NaN,NaN,NaN,NaN,1.984335,NaN,NaN,NaN

In [15]:
fdf_appl = fdf_appl.dropna()
#fdf_appl = fdf_appl.drop(columns = 'SMA 100')
fdf_appl.head()

,date,ticker,close,return,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30
24771,2023-11-01,AAPL,171.648407,1.873851,168.491135,168.017502,165.975174,168.816727,167.759027,169.312033,172.510280,171.867802,174.296028,1.673380,1.324768,1.092395,1.082177
25267,2023-11-02,AAPL,175.200394,2.069339,171.648407,168.491135,168.017502,164.662918,169.866522,169.520215,172.641505,171.987517,174.225975,0.742189,1.489237,1.176677,1.134114
25763,2023-11-03,AAPL,174.292679,-0.518101,175.200394,171.648407,168.491135,165.975174,171.530023,169.892184,172.600065,172.048690,174.231304,1.093133,1.403532,1.136199,1.136275
26259,2023-11-06,AAPL,176.838272,1.460528,174.292679,175.200394,171.648407,168.017502,173.294177,170.506873,172.611906,172.152290,174.243539,1.110617,1.454432,1.168662,1.158975
26755,2023-11-07,AAPL,179.393692,1.445060,176.838272,174.292679,175.200394,168.491135,175.474689,171.333690,172.781118,172.476571,174.275704,1.032927,1.492699,1.207870,1.092175

In [16]:
len(fdf_appl)

703

In [17]:
fdf_appl['future return'] = fdf_appl.groupby('ticker')['return'].shift(-1)
fdf_appl = fdf_appl.dropna()
print(len(fdf_appl))
fdf_appl.head(len(fdf_appl))

702

,date,ticker,close,return,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return
24771,2023-11-01,AAPL,171.648407,1.873851,168.491135,168.017502,165.975174,168.816727,167.759027,169.312033,172.510280,171.867802,174.296028,1.673380,1.324768,1.092395,1.082177,2.069339
25267,2023-11-02,AAPL,175.200394,2.069339,171.648407,168.491135,168.017502,164.662918,169.866522,169.520215,172.641505,171.987517,174.225975,0.742189,1.489237,1.176677,1.134114,-0.518101
25763,2023-11-03,AAPL,174.292679,-0.518101,175.200394,171.648407,168.491135,165.975174,171.530023,169.892184,172.600065,172.048690,174.231304,1.093133,1.403532,1.136199,1.136275,1.460528
26259,2023-11-06,AAPL,176.838272,1.460528,174.292679,175.200394,171.648407,168.017502,173.294177,170.506873,172.611906,172.152290,174.243539,1.110617,1.454432,1.168662,1.158975,1.445060
26755,2023-11-07,AAPL,179.393692,1.445060,176.838272,174.292679,175.200394,168.491135,175.474689,171.333690,172.781118,172.476571,174.275704,1.032927,1.492699,1.207870,1.092175,0.588496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372950,2026-08-14,AAPL,305.929993,0.219479,305.260010,302.250000,304.910004,313.059998,305.322003,307.481482,318.219887,318.552157,308.950681,1.036325,1.194857,2.144831,1.989030,-0.111135
373453,2026-08-17,AAPL,305.589996,-0.111135,305.929993,305.260010,302.250000,308.260010,304.788000,307.724625,317.183958,318.325470,308.843245,0.843827,1.038062,2.106093,1.973547,1.452928
373956,2026-08-18,AAPL,310.029999,1.452928,305.589996,305.929993,305.260010,304.910004,305.812000,307.816284,316.312579,318.313393,308.902341,0.916060,0.943478,2.138330,1.989058,2.193332
374459,2026-08-19,AAPL,316.829987,2.193332,310.029999,305.589996,305.929993,302.250000,308.727997,308.426080,315.873619,318.437061,309.213337,0.930132,1.162220,2.204919,2.022921,-1.745415
374962,2026-08-20,AAPL,311.299988,-1.745415,316.829987,310.029999,305.589996,305.260010,309.935992,308.341998,315.369476,318.282143,309.633345,1.518332,1.307941,2.219795,2.042531,-0.626400

In [18]:
features = ['close', 'return', 'Lag 1', 'Lag 2', 'Lag 3', 'Lag 5', 'volatility 5', 'volatility 10', 'volatility 20', 'volatility 30','SMA 10' ,'SMA 20','SMA 30','SMA 50']
x = fdf_appl[features]
y = fdf_appl['future return']

In [19]:
split_index = int(0.8 * len(fdf_appl))

x_train, x_test = x.iloc[:split_index], x.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

In [20]:
from fastai.tabular.all import *
split_index = int(len(fdf_appl)*.8)

In [35]:
! pip install xgboost
import xgboost as xgb

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)

In [30]:
model = xgb.XGBRegressor(
    n_estimators = 200,
    max_depth = 20,
    learning_rate = 0.1
)

In [31]:
from sklearn.metrics import mean_squared_error
model = model.fit(x_train, y_train)

predictions = model.predict(x_test)
error = mean_squared_error(y_test, predictions)
print(error)

4.675332842520823

In [42]:
models = []

for i in range(25):
  for j in range(10):
    for k in np.arange(0.05,0.2,0.05):
      model = xgb.XGBRegressor(
        n_estimators = i,
        max_depth = j,
        learning_rate = k)
      model = model.fit(x_train, y_train)

      predictions = model.predict(x_test)
      error = mean_squared_error(y_test, predictions)
      models.append((i,j,k,error))
      print(error)

3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.27886155446723
3.170828267407816
3.1908949579441352
3.21713917132564
3.249560915059083
3.154447581983537
3.1534237285158904
3.153867547829526
3.155779041067549
3.1545940941149886
3.1537148378332938
3.1543013373723716
3.1563535939347704
3.1546528449296036
3.1541408980015926
3.1554032695518313
3.1584399572458826
3.154757047370884
3.1546548853560195
3.1566326203765747
3.1606902536012265
3.1583578308836184
3.162128860140684
3.1682521973110664
3.1767278389563227
3.1607260406647084
3.166998970897002
3.17575790067405
3.1870028243789634
3.1610501171696943
3.167652398997314
3.1767459540340663
3.188330777673746
3.1621044888517233
3.16988650346795
3.180285155348764
3.1933004371077844
3.1622145565895
3.1700970691023675
3.180586646913607
3.193683286001643
3.1901489776290717
3.1927218261840156
3.2433613531587824
3.310025419130974
3.1534363729038977
3.1554477793747053
3.1624152794788865
3.173800418788803
3.1537203089571273
3.155994383516708
3.1632043413406215
3.1748127334741754
3.1538748097112688
3.156608937686974
3.1645845408487694
3.1772641974416977
3.1546088168115785
3.158637297159367
3.1681313542396525
3.1826629433789777
3.1575349352918813
3.1649325722978796
3.182755793107598
3.205903416439365
3.1674464598498604
3.187706330928323
3.215130330143612
3.2374057983192586
3.1644395083627836
3.182827176565579
3.2110577611516558
3.1777039898777324
3.1620033382054804
3.1863226071138135
3.2277814093714516
3.1698690759326094
3.1741091623519155
3.2111057975551236
3.16632691698761
3.1988503396527537
3.1843321854551627
3.233919476510077
3.3233437536159536
3.428718260202283
3.153764484951815
3.1619578331343035
3.179269982267189
3.180908710613744
3.1541773855985245
3.1627291175704437
3.1804592144330943
3.2036398266862065
3.1546712425422188
3.163507156300265
3.182112978006597
3.202319008641446
3.1558898249379155
3.1674423229575157
3.1895793311186136
3.2256654116686843
3.1625795804122734
3.1747323822983113
3.2358763897017675
3.276859407692683
3.175540819062697
3.178361942844121
3.2116017348923407
3.3496975087304075
3.172674644041894
3.2135922925546696
3.270907940214226
3.2340819182998
3.182467566835415
3.2150682996432223
3.2262362719319024
3.2264147077443663
3.183662330028174
3.213237655280831
3.2323183267384623
3.426831250498807
3.2087158315725217
3.288536412836587
3.4527818700892943
3.6333057998438285
3.155301639711516
3.172058956142041
3.1844680691951486
3.2111516877550534
3.1558356207331837
3.1730999020552755
3.2002766303841383
3.2060983956201667
3.156419740673399
3.1739640497896637
3.1981738694232793
3.2682742350517135
3.1587432387835275
3.180469160087204
3.271755163850344
3.296984301272438
3.165460506349557
3.1983656165967904
3.2808778896922908
3.36040697888519
3.1860585155929138
3.2027547090345925
3.250622606036779
3.495429351872833
3.185059396066783
3.2353281683844
3.307693405643338
3.2545092665188977
3.1959052086662023
3.212142335748025
3.282717079711275
3.3139158022160853
3.183211077958386
3.2309747465159333
3.266745570812062
3.543335921124557
3.216610421170056
3.3469720349091006
3.545764155710054
3.7334352097496932
3.15792751788771
3.1752712336570292
3.185752849510669
3.2135632397626837
3.1585752304009898
3.1852906372889422
3.2016967551604285
3.2557921547251283
3.159202011827155
3.1886138072208636
3.246057248473879
3.2737728548372576
3.162670875380894
3.199347321640072
3.316601949071238
3.344283082026258
3.169737805549716
3.2245357935450656
3.3453494175113976
3.394290625577
3.180213008163544
3.225280094004576
3.2804496910000163
3.5198901129682265
3.1961723711845265
3.2687988073627947
3.315385452394108
3.2993498123989697
3.2088677465093465
3.2289279775902218
3.329692521266802
3.2854810158095473
3.1814627679472154
3.2357137117630765
3.317739882017545
3.597148410052003
3.2381073954214035
3.435715416950016
3.636935761540344
3.945938055061589
3.161531062873898
3.1883076934038597
3.207469124073072
3.214343055782277
3.1622856524664416
3.185866136359888
3.238424217523453
3.262033260602198
3.1635033220339586
3.2015471158403632
3.3061968127585697
3.35979007291108
3.1671971689769545
3.238396551627273
3.352008406910744
3.3895714119792912
3.1753455370878934
3.273204271658351
3.3509759849646232
3.4000830837298697
3.190996068541374
3.2598095135783236
3.3274852508153794
3.4989513882489844
3.212116460179906
3.3150215075477294
3.369091404111642
3.318607315022805
3.223128295649898
3.2891028743572197
3.37840625915051
3.3769855419318073
3.2040624876994888
3.273472871449853
3.3705798416131105
3.646218662187186
3.257881640111749
3.486125605779571
3.7200324793136894
4.019186474728914
3.1660098234562373
3.188928253232035
3.2079864826336775
3.2421652515732418
3.166900638619767
3.2106691726337955
3.243196767189393
3.2906164300491723
3.1681636926934895
3.209040211727106
3.3427384142663765
3.4433682759827278
3.173111931467137
3.253899134445843
3.3714609742588677
3.4189315288657225
3.1808962797161433
3.290070185604798
3.349815083751772
3.4912649855852984
3.2028282259935987
3.282960258835798
3.4418839174498492
3.4671433133597986
3.210140405977831
3.380475093598179
3.3726189266455964
3.377771712777982
3.221046161927091
3.3032490051683308
3.432010969284244
3.4331979191532334
3.211167309162749
3.3162673067537423
3.446231079214706
3.749638911317532
3.2829741483729085
3.5418783961698423
3.817241523752705
4.087567160508835
3.1674889569376306
3.202770385797198
3.2073682342627405
3.241029018348654
3.1724542919476018
3.2247614238706808
3.2472038801708067
3.268000241870526
3.173595727238892
3.2407874629755278
3.364469536471011
3.4406707322825305
3.17909935356223
3.30779399180911
3.407824834088552
3.4176884812452935
3.1928197623743837
3.3033513470418185
3.352519723687288
3.5053024538026927
3.2099265768959286
3.2965263801610125
3.46591574289831
3.5100279018201483
3.220961568512854
3.4005253726360736
3.3984498102238305
3.4673837228570727
3.2383815096495994
3.3344816510944724
3.4875685183231973
3.458281104069938
3.2280415505566444
3.339074511021184
3.4771350969504584
3.754563201464219
3.31043189428185
3.61400111649354
3.906793931459364
4.161118055467123
3.172779626394755
3.2063082163807666
3.2285970248500506
3.248031555426654
3.177658191992938
3.2278115713353266
3.308060250481038
3.272792713256338
3.1774997351565095
3.2554268938250037
3.4034277121245924
3.4930176553041776
3.187811635686027
3.3484323435856735
3.4468321039362397
3.432327600687245
3.19982966867707
3.3402560116953146
3.398354441837577
3.498264146297714
3.2220902640016043
3.297979419702293
3.582801852485888
3.486107836179677
3.2401341994487813
3.3954381231689537
3.4187268843758045
3.548228634301344
3.2560528424377853
3.3537968592104304
3.492215693414594
3.4448383345025606
3.2430325431771965
3.3613900870353497
3.50999456945428
3.9019572398086915
3.344422813829508
3.6903442686258634
3.98665143030995
4.306177825727756
3.178759698899946
3.2066832505318774
3.23384000895143
3.2487503538486338
3.1840175710141763
3.2619653260898906
3.30654331804995
3.293192244014551
3.1810578627817816
3.2919578424907736
3.478826551817131
3.490899656187043
3.194613560311768
3.369457536801446
3.449551076751139
3.4986958837851887
3.2226710873001063
3.3367942863527262
3.4128933533414973
3.5186383072297995
3.247437633160105
3.3375383605913433
3.6204910517144095
3.47348372361103
3.251122626595111
3.408898438285411
3.4365536865314974
3.5555359135662723
3.262457299001803
3.3773948843394446
3.514161261430868
3.496404201315027
3.2696432417784047
3.410307410631862
3.522472076957095
3.9434758335574975
3.3812138356971913
3.7378391626326084
4.052943862381074
4.333872875671598
3.180390765837591
3.206070103980542
3.234372652896982
3.2541284688289145
3.1840014115027824
3.274376230569552
3.310564010675561
3.3033995783931847
3.1968057323431736
3.3381936707244804
3.478287010356758
3.546914295194661
3.21937450680856
3.405879607550368
3.494536862952769
3.478948929799862
3.2296988631005266
3.3532134878733237
3.4189530694778134
3.5311320125832686
3.2565559412655656
3.385815915303333
3.6393946321749344
3.4775291727561153
3.264202861969384
3.4459049971876285
3.491607133911236
3.5833953270921195
3.2756868495779994
3.4252302831621515
3.5276927506219407
3.535489957279999
3.281208305588385
3.4356642125257006
3.550967193329997
3.9317858442135125
3.408816654119755
3.7897352049447988
4.108011946454208
4.382297093145243
3.1805340826762287
3.220671177943987
3.2376962019098787
3.2808887595831124
3.196142026575256
3.272447040053258
3.3313820728312824
3.382109969060941
3.201639043581336
3.3505292237300592
3.4840331704304393
3.555750742253034
3.2451690163668294
3.436630219860297
3.5319248472516334
3.4695454075216556
3.2423148196025813
3.3982394627368127
3.4791758999364832
3.5640688477016567
3.264289483639672
3.394147691882116
3.634892153994137
3.490609786871505
3.2907303927042943
3.466306028475815
3.487731993979448
3.670074763967742
3.294320952607674
3.419714300340379
3.5607090294631902
3.5956194953343217
3.3107916762592287
3.4909448722933054
3.5922048782581375
3.9811501668131153
3.4469225537028243
3.8468909468388053
4.166279029608776
4.414732094587621
3.1871555336621054
3.222314678359804
3.2576570375416107
3.279667345254713
3.2029634467961454
3.2750598871356544
3.3369363389081856
3.3807205541213787
3.2072775279480354
3.35523354147313
3.5011319216973105
3.5830013536992884
3.251788814848254
3.4607706324372867
3.536636523832886
3.4755690866507964
3.2585106540004776
3.392681039493502
3.4917166055449393
3.59333056713713
3.2590128456827445
3.423466372053278
3.6882795886885242
3.5069273537835124
3.300611439347682
3.506389136580932
3.5022617964025624
3.669480741459349
3.3083386875971597
3.452240534119826
3.6182784055563455
3.585088584535638
3.329739771161023
3.53506747917851
3.631163257527643
3.9703846424285936
3.4748631475043616
3.8861694037303334
4.206414955389053
4.497320195626633
3.1888507832773536
3.22264578260788
3.2555069529502236
3.263580465092548
3.2034022960900588
3.277984421617187
3.3361104115797877
3.405460657505389
3.210470586767572
3.3544879324955437
3.4885591357560704
3.664802973868927
3.269835187656696
3.4971384386917523
3.540204651450361
3.4731730818379547
3.2845815654594372
3.389933893639284
3.5060386092584697
3.582801444092489
3.2834179875614042
3.4884803778775315
3.713436113777861
3.5232536487687147
3.3164720596278294
3.5306201593475643
3.4988555681498767
3.723757675242328
3.325703996386175
3.4681115463981134
3.628902983286606
3.6345308207292115
3.3449296963421276
3.5754452150187332
3.663208302903335
3.9913790752071283
3.5042821622900204
3.939833311953077
4.281251360246959
4.547608060908856
3.1956589045548704
3.235819489268875
3.2784759550002835
3.2922008885714957
3.2200553844930653
3.317737343191736
3.3351229227529804
3.427846024001238
3.225997756589578
3.3779548577384393
3.488169636184456
3.6774948366707934
3.289209727875727
3.5088988086170096
3.540193685413386
3.4973169687387027
3.3038223528949016
3.4160347571646117
3.5199678560519687
3.5564772821646664
3.2830261533432683
3.497671485251657
3.7444602544400585
3.5001473625855892
3.3078546663585358
3.5325328403479084
3.556466436582611
3.7827921771293207
3.3461988129640647
3.480935248097866
3.6549047667070425
3.656287909781041
3.3654522844829975
3.657268969243642
3.6935494831514117
3.990459796133918
3.537206537212056
3.9762934027874075
4.338838867662766
4.579984281291138
3.1958354935065643
3.239313632330554
3.2635840727396723
3.289281435036482
3.2237192231927767
3.3322551967964036
3.352972028406134
3.4093044282709406
3.239097235895689
3.375834850532614
3.4949481243292544
3.6420458120079315
3.299547300222099
3.5173625162327573
3.552279255283178
3.5241594734613435
3.332144450172775
3.488987632573155
3.5196988837027368
3.571975334933702
3.297930283459618
3.5840273292524296
3.751557909228904
3.5209175652025193
3.303972240089832
3.5519748685706998
3.553325453447097
3.7800877537776674
3.3930168746494784
3.5098294137594714
3.674111838233249
3.6761358485339306
3.3782831043992023
3.6477690326287946
3.7303862306340783
4.021576598306508
3.5692232679334777
4.006112055798236
4.399502960773269
4.6218319338347635
3.1962549975580603
3.2396524921085956
3.2640248313652194
3.2898653684818804
3.2253289087622927
3.3357348067181274
3.336151826204534
3.4342310414236756
3.2509818959578287
3.411745059406544
3.4970280636573867
3.6688447726107145
3.3261572701666786
3.5184459124962024
3.5670408928171335
3.5644061246281007
3.3570862165943405
3.5005461330913885
3.576320804881492
3.5457130903998357
3.3011570712147362
3.585439777800537
3.772252353645315
3.5651534604650963
3.3201978483398764
3.573228176089507
3.589110695227746
3.7993882348557118
3.402464531043649
3.526668823299411
3.6695840038566043
3.6758155066511
3.4009629782094435
3.682129157931392
3.7506561171803012
4.058274993180995
3.607482859463292
4.036951664967983
4.464559984529657
4.651414481952537
3.2032882673413483
3.2359823515580497
3.263202071274835
3.3213935373246675
3.2261200640124494
3.34940912753162
3.3965388417701403
3.4342195719013846
3.2723180909652236
3.401731693116667
3.5534687080196297
3.672073309890478
3.3365922984666443
3.5121077877761406
3.590444937509406
3.586065070101977
3.3715067645398724
3.4810986326384676
3.5760038353741876
3.553429508628251
3.3102072292952087
3.591151805922645
3.785646292888119
3.5782354037779034
3.3248224450162773
3.5848976954887655
3.5851679965574874
3.850051190429777
3.411127986037323
3.5532171953462877
3.6631768358056513
3.674597407507895
3.423266434683582
3.684920680538323
3.7531816936033375
4.089584467288326
3.6451810840288634
4.067594247990165
4.511209352558153
4.675412561834982
3.203459183930015
3.25145975336058
3.286791529913742
3.2990445752933617
3.2385229973810863
3.3531790558618826
3.402717037271975
3.4332809187702504
3.2908021874988207
3.399013430409256
3.5558684799027143
3.6707617632806975
3.356679581975698
3.5263812066646443
3.632892811041364
3.5629803415465044
3.399586313163936
3.4874733065201466
3.6153793904359692
3.56991229804847
3.3355173043776887
3.59702313154257
3.779017428642401
3.5793355986574356
3.3358807029004174
3.5840641355443927
3.5886629015892804
3.849341315296473
3.4289537893947744
3.5689141131296824
3.6609441912755556
3.7151517029158767
3.45322712619806
3.7187206203615384
3.770261594123777
4.085130604707912
3.6714654725299685
4.0815586758200055
4.559844962018105
4.6977761040939665
3.203155403379149
3.249933548964059
3.2826245988137375
3.294447559302561
3.240102351995272
3.355601612394243
3.4061878984868055
3.470994142004473
3.2928663339192457
3.429914809483848
3.6098357666879286
3.7244111775401865
3.370809355973437
3.5286436033507473
3.64915585484125
3.5677793860630063
3.420343201874774
3.4831880044605894
3.616342990745004
3.5680527915708433
3.3517801920789503
3.606400523200125
3.8016297086345316
3.586851415284603
3.3600167318508807
3.6046696582888584
3.5964746037810578
3.860996644086328
3.4512883062928297
3.567604994067322
3.6413030725124775
3.7433834533658454
3.471054900061104
3.73603858670219
3.7943005341440905
4.086531181776825
3.709659680805773
4.101169201391782
4.588438332460316
4.715865219936404
3.2097899799296923
3.2621727135410556
3.267628283365237
3.3184387577366325
3.2411105171398353
3.3567818558822595
3.444205869030177
3.4707619738469395
3.3116376397559577
3.4581627636433088
3.6002413828192057
3.7104916779955226
3.388043686998877
3.544730445694026
3.6659205392542233
3.5880779110388255
3.430240818452903
3.483811278602212
3.62100346102443
3.5763927305838545
3.353357654232421
3.5907355745048766
3.813653664846449
3.6180665249577455
3.3858067960569347
3.6084180476650567
3.599789359954009
3.8656786404389987
3.469666639158032
3.5698286890708824
3.702667310225289
3.715994629649937
3.5073002380324296
3.7471716972576705
3.763057326228115
4.121323479982093
3.7520824471777794
4.127328550105435
4.612982768983368
4.733158644573644
3.211502715798651
3.26483586359672
3.2860901362270316
3.3008965269400767
3.2583141705545042
3.3981505795856157
3.435383934207006
3.5105688041117182
3.323929496015361
3.4909651468163982
3.6383330447424926
3.7106905651175786
3.4013723648692933
3.5541749530728737
3.654050737415603
3.5878512801919107
3.434677252682459
3.503920189646272
3.6444512045579396
3.5884210574944224
3.3727168074084215
3.585331072530661
3.8118434456544086
3.667717979110584
3.410427253763426
3.6341387352915926
3.6075517457313704
3.86956580717591
3.4749010174293367
3.5606159431991697
3.6978248584453173
3.7184274063621476
3.5272593841558724
3.764104543547222
3.760834035429698
4.145888617590979
3.7806476360874184
4.1651152597135095
4.647074421182603
4.747857957967966
3.212170414534288
3.264421895550502
3.290849756192774
3.329463634007204
3.257253141351519
3.3859455151701043
3.4537130165138303
3.508967079283766
3.339396407151736
3.4885258117140086
3.6299055700950564
3.7269949823236197
3.410356694379044
3.5638768690736122
3.66855346882553
3.602150976745012
3.4568526916557274
3.5040899790608027
3.6661541439577623
3.6292568588375835
3.3983458414465293
3.5849344380789874
3.808507903761658
3.6408225053101964
3.4181048751957057
3.637781348636244
3.6084436263210105
3.8695341874008196
3.477604195402156
3.575977796204292
3.6894269926359735
3.724442147687198
3.561150251510892
3.7956262940641
3.7765745341245203
4.155426365032001
3.811552419180759
4.19969278693251
4.676870398034894
4.7645482105446835
3.2123367409607346
3.2647103172518945
3.288345063177849
3.31193917149554
3.2641291343312506
3.412007614633071
3.4659774716379075
3.51401863195474
3.345743874235814
3.4929195367586487
3.6326442956902136
3.7268955274856657
3.415074732208319
3.5696144356134396
3.666144721728297
3.6290405387161093
3.453714167806931
3.503709216848357
3.6653718651995018
3.6654135875611047
3.4260797225862953
3.5933060097652634
3.8123019129110114
3.6409545524899456
3.4224631173719615
3.6432131562253356
3.6086327626349397
3.8880775667392844
3.4872522754579913
3.562920900901264
3.694598368588331
3.718877087316976
3.5625701916925734
3.820269329323969
3.7817194413057984
4.14424922432282

In [44]:
min_score = 1000
for i in range(1000):
  if (models[i][3] < min_score):
    min_score = models[i][3]
    best_model = models[i]
best_model

(1, 1, np.float64(0.1), 3.1534237285158904)